twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

framework:
    error_controller: 'App\Controller\ExceptionController::showException'

when@test:
    twig:
        strict_variables: true
        cache: false
        
when@dev:
    twig:
        strict_variables: true
        cache: false
